### ISSUE TITLE
Hash tag support for constructor

### ISSUE THREAD

**Issue by podhy** [Haehnchen/idea-php-symfony2-plugin#1015]
Hello,
I discovered this cool feature and tried to use it, but it doesnt work with constructor parameters.

My enviroment is:
* PHPStrom 2017.2.2
* Symfony plugin 0.14.151

**Comment by King2500** [comment]
Related to https://github.com/Haehnchen/idea-php-toolbox/issues/50 ?

**Comment by Haehnchen** [comment]
I think he meant:

```php
__construct($foo, $foobar);
```

```yaml
services:
  Foobar\Bar:
    arguments:
      foo: '@my_service'

```
