### ISSUE TITLE
[3.4][Completion] Support Simpler injection of tagged services

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#1039]
```yml
services:
    App\Manager\TwigManager:
        arguments: [!tagged twig.extension]
```

```xml
<services>
    <service id="App\Manager\TwigManager">
        <argument type="tagged" tag="twig.extension" />
    </service>
</services>
```

https://symfony.com/blog/new-in-symfony-3-4-simpler-injection-of-tagged-services
