### ISSUE TITLE
"Missing Parameter" warning in services.yml

### ISSUE THREAD

**Issue by no7mks** [Haehnchen/idea-php-symfony2-plugin#1049]
Is it possible to disable the "missing parameter" warning in services.yml? 

Given the following services.yml:
```yaml
parameters:
    dir:
        log: /data/logs
services:
    logger:
        class: CustomLogger
        arguments: ["%dir.log%"]
```

the reference of parameter 'dir.log' is reported as missing parameter. However, we have a plugin that supports this kind of interpretation of array parameters. So, my question is that, is is possible to disable this warning or support the nested array parameters?
