### ISSUE TITLE
Add autocomplete for classes in YAML services definition

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-symfony2-plugin#1054]
(Couldn't find an existing issue for this..)

```yaml
services:
    <caret>
```

Since Symfony 3.3 the recommended id for services is their FQCN:

```yaml
services:
    _defaults:
        autowire: true

    AppBundle\Service\MessageGenerator: ~
```
```php
$container->get(MessageGenerator::class)->foo();
```

... or when `autoconfigure` is set, a namespace prefix:
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository}'
```

Ideally `_defaults` is included at that caret position for completion.
