### ISSUE TITLE
"Provided instance of service id does not match argument" in services.yml

### ISSUE THREAD

**Issue by lashae** [Haehnchen/idea-php-symfony2-plugin#1063]
I have a wrapper around my `app` doctrine connection which is defined as follows in `config.yml`:

```
doctrine:
    dbal:
        default_connection: master
        connections:
            master:
                driver:   pdo_mysql
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                server_version: 10
                charset:  UTF8
            app:
                driver:   pdo_mysql
                host:     ~
                port:     ~
                dbname:   ~
                user:     ~
                password: ~
                server_version: 10
                charset:  UTF8
                wrapper_class: AppBundle\Util\Multitenancy\ConnectionWrapper
```

Wrapper class `AppBundle\Util\Multitenancy\ConnectionWrapper` extends `Doctrine\DBAL\Connection` as required:

```
<?php

namespace AppBundle\Util\Multitenancy;

use Doctrine\DBAL\Connection;
use Doctrine\Common\EventManager;
use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\Driver;
use Doctrine\DBAL\Event\ConnectionEventArgs;
use Doctrine\DBAL\Events;

class ConnectionWrapper extends Connection
{
  // ...
```

However in the `services.yml` I get an error for the first argument of the service named as `app.multitenancy_listener`. The error is: "Expect instance of: AppBundle\Util\Multitenancy\ConnectionWrapper Provided instance of service id does not match argument"

The service is defined as follows:

```
    app.multitenancy_listener:
        class: AppBundle\EventListener\MultitenancyListener
        arguments:
            - '@doctrine.dbal.app_connection'
            - '@doctrine.orm.master_entity_manager'
            - '@security.token_storage'
            - '@security.authorization_checker'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand, priority: 255 }
```

And here is the screenshot:
![image](https://user-images.githubusercontent.com/20574/31910146-3e5802b2-b845-11e7-9c54-f5b119ae9366.png)

I tried clearing the index of the plugin for the current project however it didn't make sense.

Is this a some sort of bug or should I configure something else?
