### ISSUE TITLE
Missing autocompletion for configurator services in DIC config files

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#1108]
Services can have a configurator, but we miss autocompletion for them:

```xml
<service>
    <!-- should autocomplete service ids, and then public methods of this service -->
    <configurator service="" method="" />
</service>
<service>
    <!-- should autocomplete class names, and then public static methods of this class  -->
    <configurator class="" method="" />
</service>
<service>
    <!-- should autocomplete PHP functions -->
    <configurator function="" />
</service>
```

**Comment by stof** [comment]
GoTo navigation would also be great.

**Comment by stof** [comment]
for YAML, there is 2 syntaxes:

service-based:

```yaml
services:
    short:
        configurator: 'id:method' # notice single colon here
    long:
        configurator: [ @id, method]
```

static method and functions just use a string using the PHP callable syntax:

```yaml
services:
    short:
        configurator: 'class::method' # notice double colon here, i.e. PHP callable syntax
```
