### ISSUE TITLE
Clickable Controller in routing.yml

### ISSUE THREAD

**Issue by Mynyx** [Haehnchen/idea-php-symfony2-plugin#111]
If a pattern contains a placholder following controller aren't clickable.

Only the first controller is clickable (Second and third: "Cannot find declaration to go to"):

```
acme_store_create:
    pattern:  /create
    defaults: { _controller: AcmeStoreBundle:Default:create }

acme_store_update:
    pattern:  /update/{id}
    defaults: { _controller: AcmeStoreBundle:Default:update }

acme_store_show:
    pattern:  /show
    defaults: { _controller: AcmeStoreBundle:Default:show }
```

All controller are clickable:

```
acme_store_create:
    pattern:  /create
    defaults: { _controller: AcmeStoreBundle:Default:create }

acme_store_update:
    pattern:  /update/
    defaults: { _controller: AcmeStoreBundle:Default:update }

acme_store_show:
    pattern:  /show
    defaults: { _controller: AcmeStoreBundle:Default:show }
```

The logic and parameters of the controller are in the meantime unmodified.
