### ISSUE TITLE
asset() autocompletion fails in PHPStorm 2017.3

### ISSUE THREAD

**Issue by yahyaerturan** [Haehnchen/idea-php-symfony2-plugin#1118]
I am using Symfony 3.4.1. In twig templates, it is not suggesting resources in public directory anymore whilst using `{{ asset('abc.jpg') }}`. It says `Missing asset...` yet it renders correctly when we display it on browsers.

This is my `framework.yaml`:

```
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: tr
    translator:
      fallbacks: ['tr']
    #csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session:
        # With this config, PHP's native session handling is used
        handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    templating:
        engines: twig
        form:
            resources:
                - 'App:Form'
```

This is my PHPStorm version:

```
PhpStorm 2017.3
Build #PS-173.3727.138, built on November 28, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2
```

Any idea how to gain autocompletion back? Because we love it 💯 percent 😄
