### ISSUE TITLE
services.yaml >> factory-created service arguments are hinted as the class being factoried

### ISSUE THREAD

**Issue by luispabon** [Haehnchen/idea-php-symfony2-plugin#1140]
Given a class that is instantiated via a factory, the arguments part refers to the factory method, not the class being generated.

So for the following YAML:

```yaml
    some.service:
        class: Foo\Bar
        factory: [ Foo\Factory, getInstance]
        public: true
        arguments:
          - '@something'
          - '@something.else'
```

The symfony plugin thinks these arguments are for the class being instantiated (`Foo\Bar::__construct`), but in fact are for `Foo\Factory::getInstance`.
