### ISSUE TITLE
[feature_request] Add an option for config inline level

### ISSUE THREAD

**Issue by alexglue** [Haehnchen/idea-php-symfony2-plugin#1142]
https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/973a3f136a5c670e092955369da8a4d663821288/src/fr/adrienbrault/idea/symfony2plugin/intentions/yaml/dict/YamlCreateServiceArgumentsCallback.java#L39

This code generate some kinda this service:

```
service.foo.bar:
    class: Service\Foo\Bar
    arguments: ['@john', '@doe', '@cat', '@dog']
```

so, could you please to add setting, which could help me to render this instead:
```
service.foo.bar:
    class: Service\Foo\Bar
    arguments: 
        - '@john'
        - '@doe'
        - '@cat'
        - '@dog'
```
?
(whis is just an inline option in default symfony config dumper) [default: 2 etc]
