### ISSUE TITLE
How to enable class autocomlete

### ISSUE THREAD

**Issue by TomasVotruba** [Haehnchen/idea-php-symfony2-plugin#1153]
Update - is there plan to add Symfony 3.3+ services based names support?

```yaml
services:
    ThisIsNotAutocompleted: ~
    # :(

    someName:
        class: ThisIsAutocompleted    
```

---

I didn't found the repository with plugin, so I'm writing here.
Just link me there, if this is not the correct repository and I will move this issues.

**How to add service autocomlete in YAML?** Something like this:

![](https://www.tomasvotruba.cz/assets/images/posts/2017/easy-coding-standard-intro/neon-autocomplete.gif)

This is from [NEON Plugin](https://github.com/juzna/intellij-neon) to PHPStorm.

Probably these classes (I don't know Java, yet):

- https://github.com/juzna/intellij-neon/blob/master/src/main/java/cz/juzna/intellij/neon/completion/ServiceCompletionProvider.java
- https://github.com/juzna/intellij-neon/blob/master/src/main/java/cz/juzna/intellij/neon/completion/ClassCompletionProvider.java

I can help, if you give me a bit of navigation, cause I REALLY miss this in Yaml :)
