### ISSUE TITLE
An Support instanceof navigation of class / interface implementation

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#1169]
```
services:
    _instanceof:
        Twig_ExtensionInterface:
            tags: ['twig.extension']
```
