### ISSUE TITLE
Provide navigation for bind arguments

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#1170]
Search for constructors with given arguments. Try to find a scope to search for services

```
services:
    _defaults:
        bind:
            $foobarHint: 'foobar'
```
