### ISSUE TITLE
Support for Twig global variables

### ISSUE THREAD

**Issue by ghost** [Haehnchen/idea-php-symfony2-plugin#118]
Hello,

Could be very useful to have support of Twig globals defined in config.yml :

``` yaml
# app/config/config.yml
twig:
    # ...
    globals:
        ga_tracking: UA-xxxxx-x
```

see: http://symfony.com/fr/doc/current/cookbook/templating/global_variables.html
