### ISSUE TITLE
[Doctrine] Repositories as services not associated with entity properly

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-symfony2-plugin#1183]
Given:
1. Doctrine entity with yaml mapping, associated with repository:
```yaml
Ololo\HelperBundle\Entity\PmCategory:
    type: entity
    table: pim_catalog_category
    inheritanceType: SINGLE_TABLE
    repositoryClass: Ololo\HelperBundle\Entity\Repository\PmCategoryRepository
```
2. Repository defined as service:
```yaml
services:
    ololo.repository.pm_category:
        class: Ololo\HelperBundle\Entity\Repository\PmCategoryRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - 'Ololo\HelperBundle\Entity\PmCategory'
```
3. Target service which accepts this repository as constructor argument:
```php
    public function __construct(PmCategoryRepository $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }
```
4. Custom method with query to repository:
```php
$category = $this->categoryRepository->find($data[self::CATEGORY_ID]);
```

Category type not resolved properly. Just object. If I injects Doctine's registry service and get repository inside constructor - it works ok.
