### ISSUE TITLE
"Provided instance of service id does not match argument" does consider factory

### ISSUE THREAD

**Issue by nCrazed** [Haehnchen/idea-php-symfony2-plugin#1210]
I have a service that is configured to be created from a non-static factory method with additional arguments.

```yaml
complex_service:
    class: AppBundle\Module\Service # __construct(A $a, B $b)
    factory: 'AppBundle\Factory:namedFactoryMethod' # function namedFactoryMethod(C $c, D $d)
    arguments: ['@AppBundle\Module\C', '@AppBundle\Module\D']
```
This yields the following warnings for the C and D arguments respectively:

* `Expect instance of: AppBundle\Module\A`
* `Expect instance of: AppBundle\Module\B`

**Symfony:** 3.4.11
**Plugin:** 0.16.165
**PHPStorm:** 2018.2
