### ISSUE TITLE
Named arguments in bind should provide navigation with 

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#1241]
```
services:
    _defaults:
        public: false
        autowire: true
        bind:
            $foobar: '@foobar'
```

Scan constructors in classes with current file scope:

```
Foobar: ~
```
