### ISSUE TITLE
Missing support for route name_prefix

### ISSUE THREAD

**Issue by nCrazed** [Haehnchen/idea-php-symfony2-plugin#1284]
See: https://symfony.com/blog/new-in-symfony-4-1-prefix-imported-route-names

## Example

The following configuration defines a single route named `admin.dashboard`. Referencing the route name triggers "Route Missing" inspections as the plugin thinks that the route name is `dashboard`.
 
```yaml
# config/routes.yaml
admin:
    resource: routes/admin.yaml
    prefix: /admin
    trailing_slash_on_root: false
    name_prefix: admin.
```

```yaml
# config/routes/admin/yaml
dashboard:
    path: /
    controller: App\Admin\Web\DashboardAction
    methods: [GET]
```

**Comment by lunetics** [comment]
Also ran into that issue today on a new project. Is there any way to help without knowing java?

**Comment by orelus** [comment]
+1

**Comment by pchelk1n** [comment]
+1

**Comment by a-menshchikov** [comment]
+1

**Comment by walva** [comment]
+1

**Comment by ptortisfi** [comment]
+1

**Comment by LanmanGroup** [comment]
there is a temp workaround?

**Comment by frostmaind** [comment]
+1

**Comment by n3o77** [comment]
With release 0.19.190 you can add the `var/cache/dev/UrlGenerator.php` in `Settings` > `Languagues & Frameworks` > `PHP` > `Symfony` > `Routing` which solves the problem.

**Comment by LanmanGroup** [comment]
Yes, from `0.19.190` version, it works!

**Comment by walva** [comment]
With Symfony 5, UrlGenerator.php no longer exists (I think Nicolas Grekas made a HUGE optimization with the routing). Now there are url_generating_routes.php and url_matching_routes.php

**Comment by Haehnchen** [comment]
yes the new format was added via: https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/71b03398eee1906f7737aea2e4d03eaec45b1c6f thats why the routes are working now and also autodetection of this was was improved.

so `UrlGenerator` or `url_generating_routes`can be taken if its not used by its own.

for me it still can be approved to also load config eg via `config/routes.yaml` to not relay on this routing file, but i guess most common usages would now work.

**Comment by walva** [comment]
It works so well! Thank you guys :D

**Comment by BenoitDuffez** [comment]
I have a similar problem but I also use hostname filtering:

```
controllers:
  resource:
    path: ../../src/Controller/yyy
    namespace: xxx\Controller\yyy
  type: attribute
  name_prefix: yyy_
  host:
    - app.site.com
    - staging.site.com
    - staging.localhost
    - test.local
    - staging.server2.com
```

This means that if I have a controller route called `abcd` then the `url_generating_routes.php` file contains `yyy_abcd.0`,  `yyy_abcd.1`,  `yyy_abcd.2`,  `yyy_abcd.3`,  `yyy_abcd.4` because of the hosts.  
However, in PHPStorm, I can definitely use `redirectToRoute('yyy_abcd', [ ... ])` and it works (Symfony will pick the route that matches the host currently being used).

So the workaround to add the URLs into the plugin configuration works for the prefix part, but not the suffix.
