### ISSUE TITLE
[BUG] name_prefix setting ignored in routing

### ISSUE THREAD

**Issue by n3o77** [Haehnchen/idea-php-symfony2-plugin#1442]
I'm on sf 4.4.7, in my annotations.yaml i'm using the `name_prefix` setting for different controller paths but it's ignored when suggesting routes

annotations.yaml:

```yaml
frontend_controllers:
    resource: ../../src/FrontendController/
    type: annotation
    name_prefix: frontend.

backend_controllers:
    resource: ../../src/BackendController/
    type: annotation
    prefix: /backend
    name_prefix: backend.
```
Suggestions:
<img width="817" alt="Screenshot 2020-04-06 at 17 15 01" src="https://user-images.githubusercontent.com/321891/78574380-3583a180-782a-11ea-8d14-3e60b37129d8.png">
