### ISSUE TITLE
missing service on state machine default bind

### ISSUE THREAD

**Issue by Wait4Code** [Haehnchen/idea-php-symfony2-plugin#1449]
Hi, 
I don't understand why, default bind in service definition shows me warning about missing service on 2 of my state_machine. Only one bind does not show any warning as you can see in capture below
![image](https://user-images.githubusercontent.com/19693378/79242297-6c823480-7e74-11ea-8079-334032b265d9.png)

Definition of theses state machine are in the same workflow.yaml file :
```yaml
framework:
  workflows:
    phone_number_life:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: method
        property: status
      supports:
        - App\Entity\PhoneNumber
      initial_marking: used
      places:
        - used
        - outgoing
        - blocked
        - left
      transitions:
        outgoing_warrant_detected:
          from: used
          to: outgoing
        to_quarantine:
          from: [used,outgoing]
          to: blocked
        to_leave:
          from: [used,outgoing]
          to: left

    outgoing_warrant_life:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: method
      supports:
        - App\Entity\Warrant\OutgoingWarrant
      initial_marking: submitted
      places:
        - submitted
        - approved
      transitions:
        approve:
          from: submitted
          to: approved

    alphalink_warrant_life:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: method
      supports:
        - App\Entity\Warrant\AlphalinkWarrant
      initial_marking: submitted
      places:
        - draft
        - submitted
        - temporary_planned
        - planned
        - rejected
        - completed
      transitions:
        submit:
          from: draft
          to: submitted
        suggest_date:
          guard: "subject.getExpectedDate()"
          from: submitted
          to: temporary_planned
        confirm_date:
          from: temporary_planned
          to: planned
        deliver:
          guard: "subject.getDeliveryDate()"
          from: planned
          to: completed
        reject:
          from: [submitted, temporary_planned, planned]
          to: rejected
        request_change:
          from: [submitted, temporary_planned, planned]
          to: draft
```

Any clue ? Resetting cache & restart has no effect.
