### ISSUE TITLE
Rename refactoring ignores constants inside yaml files

### ISSUE THREAD

**Issue by sabat24** [Haehnchen/idea-php-symfony2-plugin#1667]
1. Create some class and add there a constant

```php
namespace App\Model;
 
final class Status
{
    public const DRAFT = 'draft';
}
```

2. Create some yaml file (in my case it's a workflow)

```yaml
framework:
  workflows:
    training_status:
      type: 'state_machine'
      initial_marking: !php/const App\Model\Status::DRAFT
```

3. Try to refactor the name of the constant in `Status` class from DRAFT to something else.

The reference to DRAFT constants won't be changed.

For example if I go to my `App\\Model\\Status.php` and refactor name from `public const DRAFT = 'draft';` to `public const DRAFT_NEW = 'draft';` IDE  should change it also in YAML to `initial_marking: !php/const App\Model\Status::DRAFT_NEW`

Is it possible to tell IDE about connection between constants used in YAML during refactoring?
