### ISSUE TITLE
Autocomplete on service references

### ISSUE THREAD

**Issue by atalavera-sellboost** [Haehnchen/idea-php-symfony2-plugin#1791]
Hello, first off thank you for this great plugin.

I have service references starting with @ like this:

```
    My\Namespace\Factory:
        factory: '@My\Namespace\Factory'
```

But the plugin isn't detecting that reference so I get a "missing service" and can't clic to open the class.
I expected to be able to navigate to class file using control clic like in other definitions.

However if I add a service definition like this, it works.

```
    My\Namespace\Factory:
        class: My\Namespace\Factory

    My\Namespace\Factory:
        factory: '@My\Namespace\Factory'
```

I have enabled autowire and autoconfigure, and also added My\Namespace resolution like this:

```
services:
    _defaults:
        autowire: true
        autoconfigure: true

    My\:
      resource: '../../../src/'

    My\Namespace\Factory:
      factory: '@My\Namespace\Factory'
```

PhpStorm 2021.3.2 Build #PS-213.6777.58, built on January 31, 2022
Plugin version: 0.23.216
Symfony 5.4.x
