### ISSUE TITLE
Add support for optional service referencesin YAML services configuration

### ISSUE THREAD

**Issue by FlyingDR** [Haehnchen/idea-php-symfony2-plugin#194]
Symfony have support for [special syntax](http://symfony.com/doc/current/book/service_container.html#making-references-optional) for defining optional service references, but currently (in v0.10.34) there seems to be no support for them.

When defining service as:

``` yaml
my_service:
  class: My\Service
  arguments: [@doctrine.orm.entity_manager, @?logger]
```

PHPStorm 7.0 reports of "Missing service" at `@?logger`, problem report disappears after removing `?` from reference definition.
