### ISSUE TITLE
Missing service warning on http client services and inner shot syntax

### ISSUE THREAD

**Issue by Wait4Code** [Haehnchen/idea-php-symfony2-plugin#2061]
Hi !
Awesome plugin ! I've personnaly have the paid version to try to support you and am currently encouraging my company to buy more for my colleagues.

I have a question though : is this normal that i get a 'Service missing' warning in my services.yml when i'm using specific HttpClient services ?

In this example, the warning is on the value of $client argument :

```yaml
  core_oxidized_connector:
    class: App\NetworkServiceProduction\RadiusOxidized\OxidizedConnector
    arguments:
      $loginUrl: '%env(url:CORE_OXIDIZED_URL)%'
      $client: '@core.oxidized.client'
```

Also, i've noticed that the short syntax for decoration seems to not be supported by your plugin. For example, i've got a warning on this declaration
```yaml
  App\Serializer\OptionalNameConverter:
    decorates: serializer.name_converter.metadata_aware
    arguments: [ '@.inner' ]
```
But not on this one : 
```yaml
  App\Serializer\OptionalNameConverter:
    decorates: serializer.name_converter.metadata_aware
    arguments: [ '@App\Serializer\OptionalNameConverter.inner' ]
```
