### ISSUE TITLE
Doesn't support multiple host routing

### ISSUE THREAD

**Issue by BenoitDuffez** [Haehnchen/idea-php-symfony2-plugin#2177]
I have a single Symfony app that is served from 3 different domains and presents a different app/UI on each.
Say it's `app.domain.com`, `www.domain.com` and `api.domain.com`.

Here is the configuration

```
config/
├── bootstrap.php
├── bundles.php
├── packages
...
├── routes
│   ├── app.yaml
│   ├── landing.yaml
│   └── api.yaml
├── routes.yaml
└── services.yaml
```

Then `config/routes/app.yaml` has the following (similar with `config/routes/landing.yaml` and `config/routes/api.yaml`):

```yaml
controllers:
  resource:
    path: ../../src/Controller/App      # this will have Landing and Api instead of App in the other files
    namespace: Company\Controller\App
  type: attribute
  name_prefix: app.                     # this will be landing. and api. in the other files
  host:
    - app.domain.com                    # this will also different in the other files
    - staging.app.domain.com
    - tests.app.domain.local
    - app.localhost
```

This creates several routes and Symfony apparently assumes it's the locale (it adds it as a `.X` suffix):

```
$ ./bin/console debug:router | awk '/homepage/||NR<4'
 --------------------------- ---------- -------- --------------------------- ---------
  Name                        Method     Scheme   Host                        Path
 --------------------------- ---------- -------- --------------------------- ---------
  app.homepage.0              ANY        ANY      app.domain.com              /
  app.homepage.1              ANY        ANY      staging.app.domain.com      /
  app.homepage.2              ANY        ANY      tests.app.domain.local      /
  app.homepage.3              ANY        ANY      app.localhost               /
  landing.homepage.0          ANY        ANY      www.domain.com              /
  landing.homepage.1          ANY        ANY      staging.domain.com          /
  landing.homepage.2          ANY        ANY      tests.domain.local          /
  landing.homepage.3          ANY        ANY      landing.localhost           /
```

Now in the IDE the routes are referenced to as `{{ path('app.homepage') }}` for example, but the plugin underlines saying the route doesn't exist and that I should pick among `app.homepage.0`, `app.homepage.1`, `app.homepage.2`, `app.homepage.3`.

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/802209/d83f5c0f-dbd3-4108-ab6d-9473cb512551)
![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/802209/2ae3fd3e-42ec-4a65-b83f-d0ffa83b7cf7)

The `url_{generating,matching}_routes.php` files both contains the routes similar to what is shown above with the `debug:router` invocation.  
It contains an additional setting: the locale:

```php
    'app.homepage.0' => [[], ['_controller' => 'Company\\Controller\\App\\HomepageController::index', '_locale' => 0, '_canonical_route' => 'app.homepage'], [], [['text', '/']], [['text', 'app.domain.com']], [], []],
    'app.homepage.1' => [[], ['_controller' => 'Company\\Controller\\App\\HomepageController::index', '_locale' => 1, '_canonical_route' => 'app.homepage'], [], [['text', '/']], [['text', 'staging.app.domain.com']], [], []],
    'app.homepage.2' => [[], ['_controller' => 'Company\\Controller\\App\\HomepageController::index', '_locale' => 2, '_canonical_route' => 'app.homepage'], [], [['text', '/']], [['text', 'tests.app.domain.local']], [], []],
    'app.homepage.3' => [[], ['_controller' => 'Company\\Controller\\App\\HomepageController::index', '_locale' => 3, '_canonical_route' => 'app.homepage'], [], [['text', '/']], [['text', 'app.localhost']], [], []],

```

I think the canonical route is exactly what Symfony expects (it will fill the locale argument based on the HTTP host).

PS: I'm sure I had submitted this a couple weeks ago but can't find it... sorry if repost
