### ISSUE TITLE
AssetMapper: Support for assets-paths

### ISSUE THREAD

**Issue by Chris53897** [Haehnchen/idea-php-symfony2-plugin#2236]
Thanks for this great plugin.

It would be great if this plugin could support the [AssetMapper](https://symfony.com/doc/current/frontend/asset_mapper.html) feature to map the paths for the assets.

Example in a twig-file.
{{ asset('apple-touch-icon.png') }}

The symfony default is, to search for assets in `public/`. 
With AssetMapper the assets are managed by default in `assets/`.
https://symfony.com/doc/current/frontend/asset_mapper.html#framework-asset-mapper-paths

After i upgraded our projects to AssetMapper and move all the files from /public to /assets, the files could not be resolved and found anymore.

config/asset_mapper.yaml
```
framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
```

Proposal:
Read the yaml-File and get the path mappings.
Try to resolve and find assets with this mapping paths.
