### ISSUE TITLE
Support for ".inner" DI alias for decorator service definition

### ISSUE THREAD

**Issue by andrew-demb** [Haehnchen/idea-php-symfony2-plugin#2237]
https://symfony.com/doc/5.4/service_container/service_decoration.html

```yaml
# config/services.yaml
services:
    App\Mailer: ~

    App\DecoratingMailer:
        decorates: App\Mailer
        # pass the old service as an argument
        arguments: ['@.inner']
```

For now, plugin emits issues about not found DI service in case of using `.inner`

> Symfony: Missing Service
