### ISSUE TITLE
Missing support for !php/const in config file as key

### ISSUE THREAD

**Issue by nicoguerinet** [Haehnchen/idea-php-symfony2-plugin#2403]
It could be nice to add support for !php/const when using as key in yaml file.

When using with workflow for example it's usefull to use constant for places.
In my configuration I had some metadata for the nodes.

The plugins don't detect a config like : 
```yaml
framework:
  workflows:
    library:
      places:
        !php/const:App\Entity\Book::INITIAL_STATE:
           metadata:
             ...
```
