### ISSUE TITLE
Go to class without namespace doesn't work from yml config

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-symfony2-plugin#271]
``` yml
    twig_cache_extension:
        class: Asm89\Twig\CacheExtension\Extension # go to class works
        arguments: [@cache_provicer]
        tags:
            - { name: twig.extension }

    twig_string_loader:
        class:        Twig_Loader_String # go to class dosn't work
```
