### ISSUE TITLE
[Feature request] Twig var autocomplete

### ISSUE THREAD

**Issue by ideea** [Haehnchen/idea-php-symfony2-plugin#31]
![infered_var_twig](http://symfony.dubture.com/images/screenshots/infered_var_twig.png)

**Comment by marapper** [comment]
Still dont work - 0.11.92 in PHPStorm 141.1408

I'd tried add this in yml files for all environments with/out includes (some of config files includes in root)

```
parameters:
  some: 22.2
twig:
    globals:
        some_variable: "Hello"
        another_variable: %some%
        set_of_vars: [1, 2, 3]
        list:
            some: 2
```

No suggest for

```
# twig
{{ so }}
```

and "Can't find declaration".
