### ISSUE TITLE
Refactor / Find Usage for translations id

### ISSUE THREAD

**Issue by sensorario** [Haehnchen/idea-php-symfony2-plugin#326]
I've a lot of $this->get('translator')->trans('some.trans.id') in my web site after 7 month of development. Now I need to reorganize all ids. I expected that this plugin can refactor ids but it is not possible. I think this is a missing feature and could be a great future. Now I've a yml file and, for example is very difficult and slow to find

```
acme.demobundle.some.stuff.foo.bar
```

strings because I've to type it by hand if is stored in yml files in this way:

```
acme:
    demobundle:
        some:
            stuff:
                foo:
                    bar: My translated string
```
