### ISSUE TITLE
Services and xdebug breakpoints problem

### ISSUE THREAD

**Issue by Moinax** [Haehnchen/idea-php-symfony2-plugin#330]
Is that possible that the plugin creates some side effect with xdebug ?

I created a service in the services.yml file

``` yaml
   homelog.ws.transformer.ad:
        class: HomeLog\WsBundle\Transformer\AdTransformer
        arguments: [@service_container]
```

But the icon to "Navigate to definition" wasn't displayed on HomeLog\WsBundle\Transformer\AdTransformer

And most importantly, I wasn't able to break (with xdebug breakpoint) in the class.

I decided to rewrite the yaml file with a copy/paste of the "Create service" phpstorm plugin which is

``` yaml
    homelog_wsbundle.transformer.adtransformer:
        class: HomeLog\WSBundle\Transformer\AdTransformer
        arguments: [ @service_container ]
```

Now the icon appear and I can break in my class.

Can you see what could be wrong ?

Regards,
