### ISSUE TITLE
Twig template finder, use configured loader

### ISSUE THREAD

**Issue by hoshsadiq** [Haehnchen/idea-php-symfony2-plugin#335]
``` yml
services:
    twig.loader.filesystem:
        class: %twig.loader.filesystem.class%
        arguments:
            - @templating.locator
            - @templating.name_parser
        tags:
            - { name: twig.loader }
    twig.loader.string:
        class: %twig.loader.string.class%
        tags:
            - { name: twig.loader }
```

[source](http://stackoverflow.com/questions/14343435/how-to-register-another-custom-twig-loader-in-symfony2-environment)

If this sort of code is registered, it should actually look through these twig loaders as opposed to ONLY the original twig loader. This would also eliminate the need for configuring the template paths manually.

I'm not sure how hard it would be to implement this but maybe you can run PHP to have it resolve the name in these cases (which is probably a performance hit, so I'm not sure if this would be a great idea).
