### ISSUE TITLE
Auto complete of assetic custom assets

### ISSUE THREAD

**Issue by hoshsadiq** [Haehnchen/idea-php-symfony2-plugin#353]
When providing custom assetic files like so:

```yaml
assetic:
    assets:
        jquery_js:
            inputs:
                - '%kernel.root_dir%/Resources/bower/jquery/dist/jquery.js'
```

It does not auto complete nor is the file clickable when including in twig:

```twig
{% javascripts filter="?yui_js" output="js/jquery.js" '@jquery_js'%}
<script src="{{ asset_url }}"></script>
{% endjavascripts %}
```

It would be nice to be able to autocomplete and make it clickable.
