### ISSUE TITLE
Alias for service not working.

### ISSUE THREAD

**Issue by ZhukV** [Haehnchen/idea-php-symfony2-plugin#391]
Hi.

Configuration:

```yml
services:
    project.entity_manager.orm:
        class: %project.entity_manager.orm.class%
        arguments: [ @doctrine.orm.default_entity_manager ]

    project.entity_manager:
        alias: project.entity_manager.orm

    project.manager:
        class: %project.manager.class%
        arguments: [ @project.entity_manager ]
```

But the service `project.entity_manager` indicate as not found.
