### ISSUE TITLE
Named assets appear as "Missing asset" in Twig templates

### ISSUE THREAD

**Issue by migmolrod** [Haehnchen/idea-php-symfony2-plugin#409]
Edit:
I forgot it. I'm using PhpStorm 8.0.2
Plugin version is 0.8
Just started a Symfony ~2.6 project (at the time I write this, it's 2.6.1)

Considering we have this in our config.yml:
```yml
# Assetic Configuration
assetic:
    assets:
        basecss:
            filters:
                - 'less'
                - 'uglifycss'
            inputs:
                - 'src/AppBundle/Resources/public/less/bootstrap.less'
                - 'src/AppBundle/Resources/public/less/library/fontawesome/font-awesome.less'
        basejs:
            inputs:
                - 'src/AppBundle/Resources/public/js/bootstrap/bootstrap.min.js'
                - 'src/AppBundle/Resources/public/js/libs/jquery-2.1.1.min.js'
                - 'src/AppBundle/Resources/public/js/libs/jquery-ui-1.10.3.min.js'
```
And something like this in one of our templates:
```twig
    {% stylesheets output="css/style.css"
        '@basecss'
    %}
        <link href="{{ asset_url }}" rel="stylesheet" type="text/css">
    {% endstylesheets %}
```

Then a warning appears under '@basecss' saying 'Missing asset'.

Screenshot:
![missingasset](https://cloud.githubusercontent.com/assets/5715026/5582040/6250e218-9063-11e4-90d4-7ed1dfa05535.png)

Exactly the same happens with basejs.

Is it only me or is there an underlying issue?
