### ISSUE TITLE
Add support for new Asset component

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#411]
https://github.com/symfony/symfony/pull/13234

```
framework:
    assets:
        packages:
            app:
                base_path: /bundles/app/
            img:
                base_path: /bundles/app/images/
```

```
{{ asset_path('images/me.png', 'app') }}
# /bundles/app/images/me.png

{{ asset_path('me.png', 'img') }}
# /bundles/app/images/me.png
```
