### ISSUE TITLE
Framework config autocompletion: assets_base_urls

### ISSUE THREAD

**Issue by tkleinhakisa** [Haehnchen/idea-php-symfony2-plugin#417]
When writing configuration file in yaml, under the framework/templating key, the plugin suggests assets_base_url when it should be assets_base_url**s** (last S letter missing)

```yml
framework:
    templating:
        assets_base_urls: ~
```

Thanks for this great plugin
