### ISSUE TITLE
Go to route in go to releated files does not work with controller as service

### ISSUE THREAD

**Issue by christiansipola** [Haehnchen/idea-php-symfony2-plugin#428]
go to related files does not find route definition when defined like this i routing/core.yml:
```yaml
login:
  path: /
  defaults: { _controller: kaustik.login.controller:indexAction }
```

getRoutesOnControllerAction() in RouteHelper.java should have a section about services maybe? My java knowledge is to low to make a pull request.
