### ISSUE TITLE
Notice that service parameter is incorrect when using abstract services

### ISSUE THREAD

**Issue by iltar** [Haehnchen/idea-php-symfony2-plugin#449]
Given the following yaml and php, a notice is triggered on the first argument of `foo.option.baz`
> Expect instance of Symfony\Component\Routing\RouterInterface

It seems like it doesn't take the parameters of the parent service into account while it should.

```yml
services:
    foo.option:
        class: Foo\Option\AbstractBaseSomethingSomething
        abstract: true
        arguments:
            - "@router"

    foo.option.baz:
        class: Foo\Option\Baz
        parent: foo.option
        arguments:
            - "@security.authorization_checker"
```
```php
abstract class AbstractBaseSomethingSomething
{
    /**
     * @param RouterInterface $router
     */
    public function __construct(RouterInterface $router)
    {
        $this->router = $router;
    }
}

class Baz extends AbstractBaseSomethingSomething
{
    /**
     * @param RouterInterface               $router
     * @param AuthorizationCheckerInterface $authorizer
     */
    public function __construct(RouterInterface $router, AuthorizationCheckerInterface $authorizer)
    {
        parent::__construct($router);

        $this->authorizer = $authorizer;
    }
}
```
