### ISSUE TITLE
Autocompletion for user returned by getUser()

### ISSUE THREAD

**Issue by gharlan** [Haehnchen/idea-php-symfony2-plugin#468]
It would be nice if we got autocompletion for the user returned by `getUser()` dependent of the configured user provider.

My user provider (propel):

```yaml
security:
    providers:
        main:
            propel:
                class:    AppBundle\Model\User
                property: username
```

Now I would like to get autocompletion for the methods of my user class in these cases:

```
// controller
$this->getUser()->...

// token storage
$tokenStorage->getToken()->getUser()->...

// twig
{{ app.user. ... }}
```
