### ISSUE TITLE
[Doctrine] Add completion for "Embeddables" of 2.5

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#471]
```
/** @Embedded(class = "Money") */
```

```
User:
  type: entity
  embedded:
    address:
      class: Address

Address:
  type: embeddable
  fields:
    street: { type: string }
    postalCode: { type: string }
    city: { type: string }
    country: { type: string }
```

http://docs.doctrine-project.org/en/latest/tutorials/embeddables.html
