### ISSUE TITLE
"Missing Translation" when using inline object in YAML

### ISSUE THREAD

**Issue by kherge** [Haehnchen/idea-php-symfony2-plugin#481]
The plugin reports that a translation is missing when it is located within an inline object.

``` yaml
user:
    authenticate:
        login:
            fields:
                submit:   { label: Log In }
```

If I do not use an inline object, the translation is found.

``` yaml
user:
    authenticate:
        login:
            fields:
                submit:
                    label: Log In
```
