### ISSUE TITLE
[Yaml] Improved YAML service definition syntax (Symfony2.7)

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#487]
Symfony2.7 will introduce new yaml service syntax. lexer is valid in PhpStorm for this, but dosnt not support this nested elements. implemention will not be that funny.

``` yaml
# app/config/services.yml
services:
    manager:
        class: AppBundle\Manager\UserManager
        arguments:
          - true
        calls:
          - method: setLogger
            arguments:
              - "@logger"
          - method: setClass
            arguments:
              - User
        tags:
          - name: manager
            alias: user
```

http://symfony.com/blog/new-in-symfony-2-7-dependency-injection-improvements
