### ISSUE TITLE
Missing service "@security.password_encoder"

### ISSUE THREAD

**Issue by gharlan** [Haehnchen/idea-php-symfony2-plugin#489]
I get "Missing Service" in PhpStorm, but the service exists since Symfony 2.6.

``` yml
services:
    my_service:
        class: MyService
        arguments: [@security.password_encoder] # "Missing Service"
```
