### ISSUE TITLE
Missing argument in services.yml doesn't keep track of factory methods

### ISSUE THREAD

**Issue by spdionis** [Haehnchen/idea-php-symfony2-plugin#492]
The missing argument inspection in services definition doesn't understand if the service is created by a factory. Example:

```yml
services:
  service:
    class: MyClass
    factory_class: MyClass
    factory_method: factory      
```

```php
class MyClass
{
    public function __construct($a, $b) {}

    public function factory() {}
}
```

I believe this was added in last update?
