### ISSUE TITLE
Decorator inner services are not found

### ISSUE THREAD

**Issue by jaytaph** [Haehnchen/idea-php-symfony2-plugin#510]
When creating a decorated service through the `decorator` keyword in the DIC, it will automatically create a service called `service.inner` (controllable through the `decoration_inner_name` service). These inner services are not known to the plugin and will be highlighted as "missing services".

**Comment by Haehnchen** [comment]
related #449 and #391

**Comment by Haehnchen** [comment]
Also annoyed me last days ;)

http://symfony.com/doc/current/components/dependency_injection/advanced.html#decorating-services

yaml
```yaml
bar:
  class: stdClass
  public: false
  decorates: foo
  decoration_inner_name: bar.wooz
  arguments: ["@bar.wooz"]
```
xml
```xml
<service id="bar" class="stdClass" decorates="foo" decoration-inner-name="bar.wooz" public="false">
    <argument type="service" id="bar.wooz" />
</service>
```
