### ISSUE TITLE
Relative resource paths in routing files

### ISSUE THREAD

**Issue by marapper** [Haehnchen/idea-php-symfony2-plugin#517]
Fastjump and suggest for relative path doesn't work if we include another routing file:

```
# routing.yml
info_monitoring:
    prefix: /some/
    resource: routing_info.yml
```

or

```
# routing.yml
info_monitoring:
    prefix: /some/
    resource: 'routing_info.yml'
```

But this works fine:

```
info_monitoring2:
    prefix: /some/
    resource: @SomeBundle/Resources/config/routing_info.yml
```
