### ISSUE TITLE
Fake routes without _controller

### ISSUE THREAD

**Issue by marapper** [Haehnchen/idea-php-symfony2-plugin#518]
Sometimes we need "fake" routes for external links (from one site to another) like

```
site_smth:
  pattern:  /smth/{id}/
  requirements:
    id: \d+
```

It helps make external urls tied and consistent for using in twig.

While route have no `_controller` (but `pattern`) we have no his route in suggest list (and throw "Missing Route" in usage).

```
{{ 'http://example.com' ~  path('site_smth')}}
```
