### ISSUE TITLE
Url hints are partial

### ISSUE THREAD

**Issue by marapper** [Haehnchen/idea-php-symfony2-plugin#519]
For example

```
# routing.yml
some_path:
  resource: @SomeBundle/Resources/config/routing_another.yml
  prefix: /section/

# routing_another.yml
some_route:
    pattern:  /info/{id}/
    defaults:
      _controller: SomeBundle:Info:info
    requirements:
      pammId:      \d+
```

In twig files `path('some_route', {'id': 1})` hinted as

```
path('/info/{id}/', {'id': 1})
```

but real url is  `/section/info/{id}/`

It's painfull also if prefix-declarations contains variables also

```
# routing.yml
some_path:
  resource: @SomeBundle/Resources/config/routing_another.yml
  prefix: /{_locale}/section/
```

Suggest doesn't contains `_locale` in parameters list.
