### ISSUE TITLE
Cannot resolve Doctrine ORM/DBAL connection services

### ISSUE THREAD

**Issue by marapper** [Haehnchen/idea-php-symfony2-plugin#520]
```
# modules.xml
<argument type="service" id="doctrine.dbal.main_connection"/>
```

where main is the name of connection configured in

```
# config.yml
doctrine:
    dbal:
        default_connection: main
        connections:
            main:
                driver:    pdo_mysql
                dbname:    %application.db.main.dbname%
                user:      %application.db.main.user%
                password:  %application.db.main.password%
                host:      %application.db.main.host%
                charset:   utf8
```

Same issue with entity managers `doctrine.orm.%em_name%_entity_manager` (doctrine.orm.default_entity_manager) exists for every em in config:

```
# config.yml
doctrine:
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: main
                mappings: ~
```

**Comment by gitomato** [comment]
I was about to post the same issue 4 years later.
Here is another example:

```yml
# config/packages/doctrine.yaml
doctrine:
  dbal:
    default_connection: conn1
    connections:
      # Service is '@doctrine.dbal.conn1_connection'
      conn1:
        url: '%env(CONN1_DB_URL)%'
      # Service is  '@doctrine.dbal.conn2_connection'
      conn2:
        url: '%env(CONN2_DB_URL)%'
```

![dbal_services](https://user-images.githubusercontent.com/10119619/54614492-cb506100-4a5c-11e9-8d73-8c84f265c25f.png)

`@doctrine.dbal.conn1_connection` and `@doctrine.dbal.conn2_connection` are not found.
