### ISSUE TITLE
"Missing service" warning on service names with capital letters

### ISSUE THREAD

**Issue by marcverney** [Haehnchen/idea-php-symfony2-plugin#537]
Hi,

I get "Missing service" warnings in PHPStorm when using service names containing capital letters, even though the case correspond to the one used in the services.yml file. The problem looks similar to a previously reported [issue concerning YML parameters](https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/179).

Example:

```yml
# src/Acme/ExtranetBundle/Resources/config/services.yml
acme_extranet.myFriends:
    class: Acme\ExtranetBundle\Services\MyFriends\MyFriendsService
    arguments: [ @service_container ]
```

The service name gets lowercased in the xml container file (see [@stof's comment](https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/179#issuecomment-28386455) in the above mentioned related issue)

```xml
<!-- app/cache/dev/appDevDebugProjectContainer.xml -->
<service id="acme_extranet.myfriends" class="Acme\ExtranetBundle\Services\MyFriends\MyFriendsService">
  <argument type="service" id="service_container"/>
</service>
```

In my Controller, the "correctly cased" service is marked as missing by PHPStorm:

```php
// src/Acme/ExtranetBundle/Controller/MyController.php
$listFriends = $this->get('acme_extranet.myFriends'); // missing service warning
```
If I change the `F` for an `f`, the warning disappears.

Thanks, by the way, for a great plugin!

Using:
PHPStorm 8.0.3
Symfony2 Plugin 0.11.93
