### ISSUE TITLE
[Twig][Translations] Translation declarations not in Unicode font

### ISSUE THREAD

**Issue by ureimers** [Haehnchen/idea-php-symfony2-plugin#552]
Hi,

I just noticed that the declarations popup for translations doesn't seem to use a Unicode font:

![Unicode characters](http://i.imgur.com/ytnOdRp.png)

The translations for German and English are correctly displayed, while the Chinese one displays the typical "◻" character.

```
# frontend.en.yml
contact_form:
  thank_you: Thank you for your inquiry

# frontend.zh.yml
contact_form:
  thank_you: 感谢您的咨询！我们会尽快与您联系。
```

I don't know if this font face is configurable in a theme, but I couldn't find it anywhere.

So if this is something a Plugin can configure it should try to use a Unicode font here. Maybe the same as the Documentation popup uses (if it's possible to get to know which one that is).

If it's a theme configuration issue than please apologize for this unnecessary issue.

Best regards and keep up the wonderful work!

Ulf Reimers
