### ISSUE TITLE
Plugin does not recognize Yml service inheritance arguments

### ISSUE THREAD

**Issue by scaytrase** [Haehnchen/idea-php-symfony2-plugin#568]
```yml
services:

  my_parent:
    class: Name\Space\Class
    abstract: true
    arguments:
    - first
    - second

  my_child:
     class: Other\Space\Class
     parent: my_parent
     arguments:
     - third
```

Symfony automatically inherits argument definition from the parent service definition, so the third argument works like third one. Plugin shows warning that `first` is incompatible types with `third`
