### ISSUE TITLE
[Doctrine] Completion with custom default repository

### ISSUE THREAD

**Issue by peterfour** [Haehnchen/idea-php-symfony2-plugin#581]
Just found this issue on my project but autocompletion is not changed when you modify your default repository with :

``` yaml
entity_managers:
            default:
                default_repository_class: AppBundle\Repository\AbstractEntityRepository
```

It would be nice to support this feature maybe support with different entity manager if not yet available
