### ISSUE TITLE
[Container] Add deprecated service definitions inspection

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#608]
```yaml
# app/config/services.yml
app.markdown_parser:
    class: AppBundle\Markdown\Parser
    deprecated: ~
```
http://symfony.com/blog/new-in-symfony-2-8-deprecated-service-definitions
