### ISSUE TITLE
Incorrect parameters autocompletion in quotes: percent character duplication in yaml

### ISSUE THREAD

**Issue by bocharsky-bw** [Haehnchen/idea-php-symfony2-plugin#624]
In `.yml` files parameters autocompletion in single/double quotes works incorrectly: duplicate `%` character at the beginning:

``` yaml
app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix:   /{_locale}
    defaults:
        _locale: '%%locale%' # should be '%locale%'
```

P.S. Without any quotes autocompletion for parameters is correct now.
