### ISSUE TITLE
[Yaml] Support inline alias

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#628]
Both valid, currently supporting only first one:
```yaml
foo:
  alias: @foo:
foo: @foo
```
see also #391
