### ISSUE TITLE
Namespaced Twig paths not working

### ISSUE THREAD

**Issue by SvetlinStaev** [Haehnchen/idea-php-symfony2-plugin#654]
Firstly, let me say that this plugin is the very best in terms of Symfony 2 integration and I really enjoy it working with it. Keep up the good work!

There is a small issue with the Twig templates when they are referenced as with their namespaced paths:

in config.yml
```yaml
twig:
    paths:
        "%kernel.root_dir%/../src/vendor/bundle/Resources/views": core
```

in the controllers:

```php
return $this->render('@core/path/template.html.twig');
```

or in the templates:

```twig
{% include '@core/path/template.html.twig' %}
```

This plugin doesn't recognise the shortcut. Is it a bug or it is not technically possible to parse the configuration to reference the namespace paths?
