### ISSUE TITLE
Registering a denormalizer results in warning

### ISSUE THREAD

**Issue by derrabus** [Haehnchen/idea-php-symfony2-plugin#661]
Let's say, I have a custom denormalizer.

```php
namespace Acme\MyApp;

use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;

class MyDenormalizer implements DenormalizerInterface
{
    /**
     * {@inheritdoc}
     */
    public function denormalize($data, $class, $format = null, array $context = array())
    {
        // …
    }

    /**
     * {@inheritdoc}
     */
    public function supportsDenormalization($data, $type, $format = null)
    {
        // …
    }
}
```

Now, I register the denormalizer using the `serializer.normalier` tag.

```YAML
services:
    my_denormalizer:
        class: Acme\MyApp\MyDenormalizer
        tags:
            - { name: serializer.normalizer }
```

The plugin's inspections now report a warning for this services, stating `Class needs to implement 'Symfony\Component\Serializer\Normalizer\NormalizerInterface' for tag 'serializer.normalizer'`.

On initialization, the serializer does not differ between normalizers and denormalizers. Usually, a normalizer implements both interfaces, but it's also perfectly valid to only implement one of the interfaces. imho, the inspection should only issue a warning if the class implements neither of the two interfaces.
