### ISSUE TITLE
 Services with autowire

### ISSUE THREAD

**Issue by zelenin** [Haehnchen/idea-php-symfony2-plugin#664]
Developer may specify service with [autowire](http://symfony.com/blog/new-in-symfony-2-8-service-auto-wiring) option in Symfony 2.8/3.0. But plugin highlight this service with ```Missing argument``` message.

Old way:
```yaml
    some_service_name:
        class: someClassName
        arguments: ['@other_service_id']
```

New way:
```yaml
    some_service_name:
        class: someClassName
        autowire: true
```

Don't check arguments if autowire option specified.
