### ISSUE TITLE
[Yaml] Automatic translation from Twig to YAML generates full path

### ISSUE THREAD

**Issue by setlord** [Haehnchen/idea-php-symfony2-plugin#708]
When I use "Create translation key" from a Twig template and select an **existing** YAML file (messages.es.yml for example), it creates the whole path to the key.

messages.es.yml before
```yaml
acme:
  index:
    main:
      title: 'Administración'
```
then I write in a Twig template
```twig
{{ 'acme.index.main.description' | trans }}
```
The plugin shows 'missing translation' and offers me to 'create translation key', I accept that, select the messages.es.yml file and it creates the whole path:
```yaml
acme:
  index:
    main:
      title: 'Administración'
acme:
  index:
    main:
      description: 'acme.index.main.description'
```

The expected behaviour (as before PHPStorm 2016.1) would be to create only the missing key:
```yaml
acme:
  index:
    main:
      title: 'Administración'
      description: 'acme.index.main.description'
```

Sorry about my poor english.
