### ISSUE TITLE
[Yaml] Extract translation not nested

### ISSUE THREAD

**Issue by rbaraut** [Haehnchen/idea-php-symfony2-plugin#711]
When extracts translations from a twig file, the translation is created but not inserted in the correct place of the yml file.

For example:

```
device:
    form:
        wifiname:
            label: 'xxx'
            title: 'xxx'
            tooltip: 'yyy'
device:
    form:
        wifiname:
            placeholder: 'yyy'

```

While the correct yml file has to be

```
device:
    form:
        wifiname:
            label: 'xxx'
            title: 'xxx'
            tooltip: 'yyy'
            placeholder: 'yyy'
```

I don't know if is a bug or is an option to configure in PHPSTORM
