### ISSUE TITLE
Monolog channel not detected as callable service

### ISSUE THREAD

**Issue by nifverdie** [Haehnchen/idea-php-symfony2-plugin#714]
When defining a **Monolog channel** in a symfony yaml service file like this :

```
my_bundle.my_service:
         class: MyBundle\MyService
         arguments: ["@kernel"]
         tags:
            - { name: monolog.logger, channel: my_channel }
```

an attached Monolog `Logger` is supposed to be (and is) available as a callable service whithin `MyBundle\MyService` :

```
        /** @var Logger $logger */
        $logger = $kern->getContainer()->get('monolog.logger.my_channel');
        $logger->debug("I don't want a warning at this point !");
```

But the plugin triggers a **"Missing Service"** warning, which is moreover not configurable in the inspection settings. Is there a way that this Monolog channel can be reconized as callable service ?

Tks,

N
