### ISSUE TITLE
support entity manager name auto-completion

### ISSUE THREAD

**Issue by MrMitch** [Haehnchen/idea-php-symfony2-plugin#731]
You can create [multiple entity managers](http://symfony.com/doc/current/cookbook/doctrine/multiple_entity_managers.html) in doctrine

```yaml
doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            foo_mysql:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: mysql
                mappings:
                    FooBarBundle: ~
            foo_sqlserver:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: sqlserver
                mappings:
                    BarFooBundle: ~
        default_entity_manager: foo_mysql
```

It would be nice if those names (`foo_mysql`, `foo_sqlserver` in the example) could be suggested by the auto-complete feature in the `getManager($name)` method of the [ManagerRegistry](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Persistence/ManagerRegistry.php#L40-L47) interface.

![image](https://cloud.githubusercontent.com/assets/576772/15396584/0d5c3ace-1ddd-11e6-9115-f07d02680a68.png)
