### ISSUE TITLE
Autocomplete for nested services

### ISSUE THREAD

**Issue by sourcerer-mike** [Haehnchen/idea-php-symfony2-plugin#738]
My services.yml looks like that:

```
services:
  crmp_acquisition:
    contract:
      related_panel:
        class: Crmp\CrmBundle\Twig\PanelGroup
        tags:
          - { name: 'crmp.panel_group', alias: 'contract_related' }
    customer:
      related_panel:
        contract:
          class: Crmp\AcquisitionBundle\Panel\Customer\ContractPanel
          tags:
            - {name: 'crmp.panel', target: 'customer_related' }
        inquiry:
          class: Crmp\AcquisitionBundle\Panel\Customer\InquiryPanel
          tags:
            - {name: 'crmp.panel', target: 'customer_related' }
```

Unfortunately I get no autocomplete when accessing a service (e.g. `crmp_acquisition.customer.related_panel.contract`).
