### ISSUE TITLE
 "Missing method" in service calls

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#755]
origin: https://github.com/Haehnchen/idea-php-annotation-plugin/issues/57

PhpStorm annotates `Missing method` in all my service calls that call a method that is in a trait.
Example :

``` yml
my_service:
    class: My\Service
    calls:
        - [setContainer, ["@service_container"]] #"Missing method"
```

``` php
namespace My;

use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerAwareTrait;

class Service implements ContainerAwareInterface {
    use ContainerAwareTrait;
}
```

The `ContainerAwareTrait` contains the `setContainer` method.

Using PhpStorm 2016.1.2 with plugin 0.12.120.
