### ISSUE TITLE
"Missing service" warning on core services

### ISSUE THREAD

**Issue by xDaizu** [Haehnchen/idea-php-symfony2-plugin#757]
The plugin marks some core services (for instance, @doctrine.orm.entity_manager" with a "Missing service" warning. At least in service declaration YML's

For instance:

License\AppBundle\Resources\config\services.yml

``` yml
services:
    app.menu_builder:
        class: License\AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager", "@router"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: top_menu }

            # The alias is what is used to retrieve the menu
        calls:
              - [ setLogger, ['@logger'] ]
              - [ setAuthorizationChecker, ['@security.authorization_checker'] ]

```
