### ISSUE TITLE
Route reference not showing in controller that is in a sub namespace

### ISSUE THREAD

**Issue by nexana** [Haehnchen/idea-php-symfony2-plugin#763]
I have a controller in my bundle that is in a sub-namespace of the controllers:

   ``` php
    namespace MyCompany\MyBundle\Controller\Rule;

    class CanApplyRuleController extends AbstractWebController
    {
           public function callAction()
           {
                 //do stuff
           }
    }
```
and the route mapping in yml:
```yml
call_my_action:
    path: /make_call
    defaults: { _controller: MyCompanyMyBundle:Rule/CanApplyRule:call }

```

- routing works correctly
- the plugin shows the correct linking to the method of the route
- plugin shows the correct reference in controllers that are in the MyCompany\MyBundle\Controller namespace

The problem is that in my controller there is no reference back to the route file. Is the plugin having problems seeing controllers that are in a subbed namespace?
