### ISSUE TITLE
The deprecation annotation about colon in unquoted YAML values has false positives

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#780]
The only case triggering an issue is having a colon followed by a space. A colon followed by another char does not cause any issue, but your plugin still reports a warning on such values.

**Comment by stof** [comment]
Actually, it looks like the remaining false positive is only when the colon is the last char of the string

**Comment by Haehnchen** [comment]
@stof any example?

**Comment by stof** [comment]
Here is a case I got, which is really weird, as there is no colon in the `^/join/[\w\-\=]++~[a-z0-9\-]++$` value being reported.

```yaml
security:
    access_control:
        - { path: ^/join/[\w\-\=]++~[a-z0-9\-]++$ }
```
