### ISSUE TITLE
Wrong "Expect instance of:" in Symfony services.yml with abstract service definition

### ISSUE THREAD

**Issue by dtatur** [Haehnchen/idea-php-symfony2-plugin#808]
> AppBundle/Admin/AbstractAdmin.php
```
namespace AppBundle\Security;
abstract class AbstractAdmin
{
  public function __construct(ContainerInterface $container, $entityClass) {}
}
```
> AppBundle/Admin/GroupAdmin.php
```
namespace AppBundle\Security;
class GroupAdmin extends AbstractAdmin {}
```
> AppBundle/Entity/Group.php
```
namespace AppBundle\Entity;
class Group {}
```
> app/config/services.yml
```
services:
    admin.abstract_admin:
        abstract: true
        arguments: ['@service_container']
    admin.group:
        class: AppBundle\Admin\GroupAdmin
        parent: admin.abstract_admin
        arguments: ['\AppBundle\Entity\Group']
```

**What is the expected result?**
The "arguments" declaration in child service definition appends the arguments to the parent arguments list. Argument "\AppBundle\Entity\Group" should correspond to the second parameter in AbstractAdmin constructor.

**What happens instead?**
Framework works fine. But Symfony plugin do not recognise abstract definition of parent service and correspond argument ''\AppBundle\Entity\Group" to the first parameter in AbstractAdmin constructor and shows inspection warning.

Clear symfony 3.1.5 install with source files to reproduce issue: [link](https://drive.google.com/file/d/0B3NvUrsaxXAzUXFEVVRtc1RCVTg/view?usp=sharing)
Screenshot from PhpStrom 2016.1.1 with warning [link](https://drive.google.com/file/d/0B3NvUrsaxXAzTFlWdEdXTG1CVGc/view?usp=sharing)
