### ISSUE TITLE
Add support for FQCN service name

### ISSUE THREAD

**Issue by hason** [Haehnchen/idea-php-symfony2-plugin#811]
Current warning: `Service Naming Conventions: Use lowercase letters for service and parameters names`

Example:

```yaml
services:
    Vendor\Namespace\Class:
        class: Vendor\Namespace\Class
        autowire: true
```
Fixes:
- https://github.com/symfony/symfony/pull/20264
- https://github.com/dunglas/DunglasActionBundle#usage
