### ISSUE TITLE
JMSDiExtraBundle support for annotation service definitions

### ISSUE THREAD

**Issue by jtreminio** [Haehnchen/idea-php-symfony2-plugin#838]
I see you added support in this ticket: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/245

I have two classes:

```
<?php

namespace FirstBundle\Entity;

use JMS\DiExtraBundle\Annotation AS DI;

/**
 * @DI\Service("mybundle.entity.answer_type")
 */
class AnswerType
{
}

```

and

```
<?php

namespace SecondBundle\Entity;

use JMS\DiExtraBundle\Annotation AS DI;

/**
 * @DI\Service("mybundle.entity.answer_type")
 */
class AnswerType
{
}

```

My config looks like:

```
jms_di_extra:
    locations:
        all_bundles: false
        bundles:
            - FirstBundle
            - SecondBundle
        directories:
            - "%kernel.root_dir%/../src"

```

Instantiating the object as: `$foo = $this->get('mybundle.entity.answer_type');` works, loading `SecondBundle`'s class first before falling back to `FirstBundle`'s.

However, the service appears undefined via PHPStorm:

![image](https://cloud.githubusercontent.com/assets/589398/21208475/083235ae-c223-11e6-9905-0c08c0a1cd8c.png)

My settings window looks like:

![image](https://cloud.githubusercontent.com/assets/589398/21208492/2c61a932-c223-11e6-8102-b65ce9dbf3ea.png)

Although that is from the annotations plugin.

Every interaction I have with your plugin has been so great, and I would love for this to work as well - is it possible?
