### ISSUE TITLE
[Container] Support new Yaml factory syntax

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#841]
```yaml
app.newsletter_manager:
    # new syntax
    factory: 'app.newsletter_manager_factory:createNewsletterManager'
    # old syntax
    factory: ['@app.newsletter_manager_factory', createNewsletterManager]

app.newsletter_manager:
    class:   AppBundle\Email\NewsletterManager
    # call a method on the specified service
    factory: 'app.newsletter_manager_factory:createNewsletterManager'
```

http://symfony.com/doc/current/service_container/factories.html
