### ISSUE TITLE
[DI] Support optional class for named services

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#847]
For a valid class name service indexer needs a class attribute, but class is now optional.

``` yaml
services:
    Vendor\Namespace\Class:
        class: Vendor\Namespace\Class
        autowire: true
```

``` yaml
services:
    Vendor\Namespace\Class:
        autowire: true
```

https://github.com/symfony/symfony/pull/21133
https://github.com/symfony/symfony/commit/306a060cc689b53d7604e07cfb294d3c379d07a6

Notes:
id converts to lower, think of empty syntax
``` 
<service id="appbundle\mytestclass" class="AppBundle\MyTestClass"/>
AppBundle\MyTestClass: ~
AppBundle\MyTestClass: {}
```
