### ISSUE TITLE
[DI] Support yaml "tags" shortcut syntax

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#849]
```yaml
App\TwigExtension:
  tags: [twig.extension]
  tags:
   - twig.extension
```
http://symfony.com/blog/new-in-symfony-3-3-added-new-shortcut-methods
https://github.com/symfony/symfony/pull/20651
