### ISSUE TITLE
[DI] Support for new factory syntax in the container configuration

### ISSUE THREAD

**Issue by skobkin** [Haehnchen/idea-php-symfony2-plugin#851]
For a long time we have support of new service factories definition syntax:

```
app.newsletter_manager:
    # new syntax
    # In this case autocomplete does not work without '@'
    # Available service methods also not visible even with '@'
    factory: 'app.newsletter_manager_factory:createNewsletterManager'
    # old syntax
    factory: ['@app.newsletter_manager_factory', createNewsletterManager]
```

It would be really nice to have it supported in Symfony plugin.
