### ISSUE TITLE
Autocomplete of asset paths in webpack-bundle

### ISSUE THREAD

**Issue by steven-prybylynskyi** [Haehnchen/idea-php-symfony2-plugin#856]
Autocompletion for [Bundle that Integrates Webpack into Symfony](https://github.com/mariusbalcytis/webpack-bundle) (alternative to assetic) is currently not avilable. 

Several [other Symfony bundles](https://packagist.org/search/?q=webpack) can be discovered with packagist, but the one created by @mariusbalcytis is imo the best

## Examples:

```twig
<script src="{{ webpack_asset('@AcmeHelloBundle/Resources/assets/test.ts') }}"></script>
<script src="{{ webpack_asset('@acme_hello/test.ts') }}"></script>

<img src="{{ webpack_asset('@AcmeHelloBundle/Resources/images/cat.png') }}"/>

{% set cssUrl = webpack_asset('@ApplicationBundle/Resources/assets/main.js', 'css') %}
```

Assetic-style blocks are also supported

```twig
{% webpack_javascripts '@ApplicationBundle/Resources/assets/main.js' %}
    <script src="{{ asset_url }}">
{% end_webpack_stylesheets %}
```
```twig
{% webpack_stylesheets '@ApplicationBundle/Resources/assets/main.js' %}
    <link rel="stylesheet" href="{{ asset_url }}">
{% end_webpack_stylesheets %}
```

## Symfony paths in stylesheets and scripts

With webpack, paths can be specified in any file for which a loader is registered, e.g. `typescript-loader`/ `css-loader`/`less-loader`/`sass-loader`/`stylus-loader`

```css
.cat {
    /* URL to generated image file will be in the css output  */
    background: url("~@AcmeHelloBundle/Resources/images/cat.png")

    /* alternative syntax  */
    background: url("~@acme_hello/../images/cat.png")
}
```

```js
require('@AnotherBundle/Resources/assets/script3.js');
```

## Aliases 

```yml
    aliases:
        additional:
            node_modules: '%path_to_node_modules%'
            bower: '%root%/bower_components'
            angular: '%path_to_node_modules%/@angular'
```

Usage example:

```js
import { Something } from '@bower/somelib';
```

Could be nice to have possibility to specify path autocompletion for such specific twig tags, like `webpack_asset`, `webpack_javascripts` and `webpack_stylesheets` in `twig` files and in any file type that one would be able to specify (e.g. `css`/`less`/`sass`/`stylus`).
