### ISSUE TITLE
"Create Method" service inspection warning raised when using double quotes in setter arguments (YAML)

### ISSUE THREAD

**Issue by aar0nr** [Haehnchen/idea-php-symfony2-plugin#875]
If you have a service definition like below, the ```"foo"``` will show trigger a "Create Method" service inspection warning. If you use single quotes, i.e. ```'foo'```, the warning does not display.

```
services:
  some_service:
    class: SomeService
    calls:
      - [someSetter, ["foo"]]
```

Plugin: 0.13.136
PhpStorm: 2016.3.2 (Build #PS-163.10504.2)
