### ISSUE TITLE
[YAML] Strange warning when having strings arguments

### ISSUE THREAD

**Issue by gnutix** [Haehnchen/idea-php-symfony2-plugin#90]
In the following YAML file, the part `@liip_imagine, 'gaufrette://gallery/` is highlighted with a "Missing Service" warning.

```
services:
    galley.liip_imagine.data.loader.stream.gallery:
        class: %liip_imagine.data.loader.stream.class%
        arguments: [ @liip_imagine, 'gaufrette://gallery/']
        tags:
            - { name: liip_imagine.data.loader, loader: stream.gallery }
```

If I transform the argument `'gaufrette://gallery/'` to a parameter (like `%gaufrette_gallery_path%`, it works well. No warnings.

May also be concerned :

```
parameters:
    gaufrette_gallery_directory: %kernel.root_dir%/../web/uploads/gallery
```

This piece of YAML (in file app/config/config.yml) triggers a warning "Missing Parameter" on `%kernel.root_dir%/../web/uploads/gallery`. If let just `%kernel.root_dir%` as the value of the `gaufrette_gallery_directory`, then it works well. No warnings.
