### ISSUE TITLE
[Twig] Add goto for global variables defined in YAML

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-symfony2-plugin#904]
**config.yml:**
```yml
twig:
    globals:
         my_var: 'Hello World'
```

**Problem:**
Goto (Ctrl+Click) in Twig templates is not working:
```twig
{{ my_var }}
```

**Comment by COil** [comment]
Do not know if it can be done, as my_var may be created by any Twig extension, not only in this twig parameter section.

**Comment by King2500** [comment]
Maybe add support for `addGlobal` method calls?

**Comment by jdreesen** [comment]
Yes, please, this would be awesome!

I have:

```yaml
twig:
    globals:
        website_settings: '@AppBundle\WebsiteSetting\WebsiteSettingReader'
```

 and am currently being forced to add

```twig
{% types {
    website_settings: '\AppBundle\WebsiteSetting\WebsiteSettingReader',
} %}
```

on top of all my templates.
