### ISSUE TITLE
Add functionality to navigate from a event listener to files dispatching that event

### ISSUE THREAD

**Issue by Ardenexal** [Haehnchen/idea-php-symfony2-plugin#932]
Example Event
```php 
$this->eventDispatcher->dispatch('foo_event', $event);
```
will take you to 
```php
class FooListener
{
function onFoot($event)
    {
       //do something
    }
}
```

example .yml

```yaml
  app.foo:
      class: Fee
      tags:
          - { name: kernel.event_listener, event: event.foo, method: onFoo }
```
## Current Functionality
* If you ctrl + click on the event it will take you to the Listener class but not the method being called

* if you ctrl + click on the `onFeeEvent` function it says that is can't find any related files

## Proposed Changes
* If you ctrl + click the event it should take you the method that is called, or a list of functions that are connected the that event

* If you ctrl + click on the `onFooEvent` it should show related dispatch calls. 

This would help with navigating through applications that use events

The ability to navigate through Symfony services already existed in both directions so is should only be a matter of extending it to check which method is being called for the search event name.
