### ISSUE TITLE
Support navigation for resource value in Symfony 3.3 service definition

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#944]
```yaml
services:
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
```
