### ISSUE TITLE
[Symfony 3.3] Service indexer should known "_defaults"

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#947]
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
```
