### ISSUE TITLE
[Symfony 3.3] Service argument inspection must respect _default configuration

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#948]
```yaml
services:
    _defaults:
        autowire: true
    
    # disable inspection
    Foobar\Class: 
       arguments: []
```
