### ISSUE TITLE
Better support for services in yaml

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#987]
origin https://github.com/Haehnchen/idea-php-symfony2-plugin-doc/issues/22

With Symfony 3.3 it is quite common to simplify service definitions from this

```yaml
services:
    myservice:
        class: App\Whatever\MyService
```

to this:

```yaml
services:
    App\Whatever\MyService: ~
```

The problem currently is that in this case the plugin does not suggest class names. it only does that for the `class:` definition.
