### ISSUE TITLE
Support for named arguments in service definitions

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#998]
For autowired services, Symfony 3.3+ supports using named arguments when one of the argument must be wired manually, instead of positional arguments:

```yaml
services:
    foo:
        class: Baz
        arguments:
            '$formatter': '@my_formatter'
```

```xml
<service id="foo" class="Baz">
    <argument key="$formatter" type="service" id="my_formatter" />
</service>
```

Currently, the bundle validates this against the type of the first argument, which is the wrong check.

note that named arguments are triggered for keys starting with a `$`. String keys not starting with a `$` have no special meaning (and are deprecated)
